#Tomcat 配置
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8004
  context-path: /
#spring配置
spring:
  #spring boot静态资源配置
  spring.resources.static-locations: classpath:/testStatic/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#数据源配置
master:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.123.115:3306/datagsbx?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: 
    password: 

#阿里云短信配置
aliyun:
  AccessKeyId: 
  AccessKeySecret: 
  regionId: cn-hangzhou
  domain: dysmsapi.aliyuncs.com
  product: Dysmsapi
#微信公众号配置
wxzjj:
  url: http://espwx.sunreal.cn/wechat/
  method: /template/sendTemplateMsg
logging:
  file: ./log/message.log